"""Static description of every LangGraph graph and its nodes.

The UI needs to draw a graph before -- and after -- anything has run, so the
topology cannot be derived from ``graph_node_runs`` alone.  This module is that
missing description: what each graph is for, which nodes it contains in order,
whether a node is deterministic or calls an LLM, and which tables it writes.

Keeping it beside ``graph.py`` is deliberate.  When a builder gains or loses a
node, this file is the neighbouring edit, and ``tests/test_agents/test_graph.py``
asserts the two stay in step rather than trusting anyone to remember.
"""

from __future__ import annotations

from typing import Any

# Node kinds.  GATE marks a human-in-the-loop checkpoint: the graph stops there
# and waits for a steward, which is a different thing from a slow node.
LLM = "LLM"
DETERMINISTIC = "DETERMINISTIC"
GATE = "GATE"


def _node(
    name: str,
    label_en: str,
    label_vi: str,
    kind: str,
    purpose_en: str,
    purpose_vi: str,
    *,
    inputs: list[str],
    outputs: list[str],
    db_tables: list[str] | None = None,
    source: str = "",
) -> dict[str, Any]:
    return {
        "name": name,
        "label_en": label_en,
        "label_vi": label_vi,
        "kind": kind,
        "purpose_en": purpose_en,
        "purpose_vi": purpose_vi,
        "inputs": inputs,
        "outputs": outputs,
        "db_tables": db_tables or [],
        "source": source,
    }


GRAPH_CATALOG: dict[str, dict[str, Any]] = {
    "G1A": {
        "key": "G1A",
        "builder": "build_understanding_graph",
        "label_en": "Graph 1A · Dataset understanding",
        "label_vi": "Graph 1A · Hiểu ngữ nghĩa dữ liệu",
        "run_en": "Run 1 — Proposal engine",
        "run_vi": "Run 1 — Bộ máy đề xuất",
        "summary_en": "Turns persisted profile evidence into a draft semantic contract, then stops for steward review.",
        "summary_vi": "Biến hồ sơ dữ liệu đã lưu thành hợp đồng ngữ nghĩa nháp, rồi dừng chờ Steward duyệt.",
        "nodes": [
            _node(
                "build_profile_digest",
                "Profile digest",
                "Nén hồ sơ",
                DETERMINISTIC,
                "Compress raw profile statistics into a compact JSON digest.",
                "Nén số liệu hồ sơ thô thành JSON digest tinh gọn.",
                inputs=["profiles", "column_profiles"],
                outputs=["dataset_profile_digest"],
                db_tables=["profiles", "column_profiles"],
                source="src/agents/nodes/profiler_node.py",
            ),
            _node(
                "data_dictionary_generator",
                "Data dictionary",
                "Sinh từ điển dữ liệu",
                LLM,
                "Normalise field names and descriptions into a data dictionary.",
                "Chuẩn hoá tên và mô tả trường theo Data Dictionary.",
                inputs=["dataset_profile_digest"],
                outputs=["normalized_data_dictionary"],
                source="src/agents/nodes/data_dictionary_generator_node.py",
            ),
            _node(
                "dataset_understanding",
                "Dataset understanding",
                "Hiểu tập dữ liệu",
                LLM,
                "Infer business role and semantic type of every column.",
                "Suy luận vai trò nghiệp vụ và kiểu ngữ nghĩa của từng cột.",
                inputs=["dataset_profile_digest", "normalized_data_dictionary"],
                outputs=["semantic_contract"],
                db_tables=["workflow_artifacts"],
                source="src/agents/nodes/dataset_understanding_node.py",
            ),
        ],
        "edges": [
            {"from": "build_profile_digest", "to": "data_dictionary_generator", "condition": "no dictionary supplied", "condition_en": "no dictionary supplied", "condition_vi": "chưa có từ điển"},
            {"from": "build_profile_digest", "to": "dataset_understanding", "condition": "dictionary already supplied", "condition_en": "dictionary already supplied", "condition_vi": "đã có từ điển"},
            {"from": "data_dictionary_generator", "to": "dataset_understanding"},
            {"from": "dataset_understanding", "to": "END"},
        ],
    },
    "G1B": {
        "key": "G1B",
        "builder": "build_rule_proposal_graph",
        "label_en": "Graph 1B · Rule proposal",
        "label_vi": "Graph 1B · Sinh đề xuất luật",
        "run_en": "Run 1 — Proposal engine",
        "run_vi": "Run 1 — Bộ máy đề xuất",
        "summary_en": "Builds candidates from a confirmed contract, tailors the prompt, then proposes typed rules.",
        "summary_vi": "Sinh ứng viên từ hợp đồng đã duyệt, viết lại prompt theo nghiệp vụ, rồi đề xuất luật có kiểu.",
        "nodes": [
            _node(
                "rule_candidate_builder",
                "Rule candidates",
                "Sinh ứng viên luật",
                DETERMINISTIC,
                "Derive raw technical checks (NOT_NULL, RANGE, UNIQUE, ACCEPTED_VALUES).",
                "Sinh các kiểm tra kỹ thuật thô (NOT_NULL, RANGE, UNIQUE, ACCEPTED_VALUES).",
                inputs=["semantic_contract"],
                outputs=["rule_candidates"],
                source="src/agents/nodes/rule_candidate_builder_node.py",
            ),
            _node(
                "prompt_customizer",
                "Prompt customizer",
                "Tuỳ biến prompt",
                LLM,
                "Rewrite the system prompt for this table's business domain.",
                "Viết lại system prompt theo domain nghiệp vụ của bảng.",
                inputs=["semantic_contract", "rule_candidates"],
                outputs=["specialized_system_prompts", "table_business_contexts"],
                source="src/agents/nodes/prompt_customizer_node.py",
            ),
            _node(
                "rule_proposer",
                "Rule proposer",
                "Đề xuất luật",
                LLM,
                "Emit structured rules with business rationale and confidence.",
                "Sinh luật có cấu trúc kèm lý do nghiệp vụ và độ tin cậy.",
                inputs=["rule_candidates", "specialized_system_prompts"],
                outputs=["proposed_rules"],
                db_tables=["rule_proposals", "workflow_artifacts"],
                source="src/agents/nodes/rule_proposer_node.py",
            ),
        ],
        "edges": [
            {"from": "rule_candidate_builder", "to": "prompt_customizer"},
            {"from": "prompt_customizer", "to": "rule_proposer"},
            {"from": "rule_proposer", "to": "END"},
        ],
    },
    "G1_FULL": {
        "key": "G1_FULL",
        "builder": "build_proposal_graph",
        "label_en": "Graph 1 · Full proposal run",
        "label_vi": "Graph 1 · Chạy đề xuất đầy đủ",
        "run_en": "Run 1 — Proposal engine (CLI)",
        "run_vi": "Run 1 — Bộ máy đề xuất (CLI)",
        "summary_en": "End-to-end Run 1 with both HITL gates inline. Used by the CLI, not the wizard.",
        "summary_vi": "Toàn bộ Run 1 kèm hai chốt HITL. Dùng cho CLI, không dùng trong wizard.",
        "nodes": [
            _node(
                "raw_profiler",
                "Raw profiler",
                "Hồ sơ thô",
                DETERMINISTIC,
                "Profile the source tables directly.",
                "Lập hồ sơ trực tiếp trên bảng nguồn.",
                inputs=["dataset_id"],
                outputs=["dataset_profile"],
                db_tables=["profiles", "column_profiles"],
                source="src/agents/nodes/profiler_node.py",
            ),
            _node(
                "profiler_digest",
                "Profile digest",
                "Nén hồ sơ",
                DETERMINISTIC,
                "Compress the profile into a compact digest.",
                "Nén hồ sơ thành digest tinh gọn.",
                inputs=["dataset_profile"],
                outputs=["dataset_profile_digest"],
                source="src/agents/nodes/profiler_node.py",
            ),
            _node(
                "data_dictionary_generator",
                "Data dictionary",
                "Sinh từ điển dữ liệu",
                LLM,
                "Normalise field names into a data dictionary.",
                "Chuẩn hoá tên trường theo Data Dictionary.",
                inputs=["dataset_profile_digest"],
                outputs=["normalized_data_dictionary"],
                source="src/agents/nodes/data_dictionary_generator_node.py",
            ),
            _node(
                "dataset_understanding",
                "Dataset understanding",
                "Hiểu tập dữ liệu",
                LLM,
                "Infer semantic roles for each column.",
                "Suy luận vai trò ngữ nghĩa của từng cột.",
                inputs=["dataset_profile_digest"],
                outputs=["semantic_contract"],
                source="src/agents/nodes/dataset_understanding_node.py",
            ),
            _node(
                "hitl_semantic_gate",
                "HITL gate 1 · contract",
                "Chốt HITL 1 · hợp đồng",
                GATE,
                "Pause until a steward confirms the semantic contract.",
                "Tạm dừng tới khi Steward xác nhận hợp đồng ngữ nghĩa.",
                inputs=["semantic_contract"],
                outputs=["pause_reason"],
                db_tables=["workflow_artifacts"],
                source="src/agents/nodes/hitl_semantic_gate_node.py",
            ),
            _node(
                "rule_candidate_builder",
                "Rule candidates",
                "Sinh ứng viên luật",
                DETERMINISTIC,
                "Derive raw technical checks from the confirmed contract.",
                "Sinh kiểm tra kỹ thuật thô từ hợp đồng đã duyệt.",
                inputs=["semantic_contract"],
                outputs=["rule_candidates"],
                source="src/agents/nodes/rule_candidate_builder_node.py",
            ),
            _node(
                "prompt_customizer",
                "Prompt customizer",
                "Tuỳ biến prompt",
                LLM,
                "Rewrite the system prompt per table.",
                "Viết lại system prompt theo từng bảng.",
                inputs=["rule_candidates"],
                outputs=["specialized_system_prompts"],
                source="src/agents/nodes/prompt_customizer_node.py",
            ),
            _node(
                "rule_proposer",
                "Rule proposer",
                "Đề xuất luật",
                LLM,
                "Emit structured rules with rationale.",
                "Sinh luật có cấu trúc kèm lý do.",
                inputs=["rule_candidates"],
                outputs=["proposed_rules"],
                db_tables=["rule_proposals"],
                source="src/agents/nodes/rule_proposer_node.py",
            ),
            _node(
                "hitl_gate",
                "HITL gate 2 · rules",
                "Chốt HITL 2 · luật",
                GATE,
                "Pause until a steward reviews every proposed rule.",
                "Tạm dừng tới khi Steward duyệt từng luật đề xuất.",
                inputs=["proposed_rules"],
                outputs=["rule_run_id"],
                db_tables=["rule_proposals"],
                source="src/agents/nodes/hitl_gate_node.py",
            ),
        ],
        "edges": [
            {"from": "raw_profiler", "to": "profiler_digest"},
            {"from": "profiler_digest", "to": "data_dictionary_generator", "condition": "no dictionary supplied"},
            {"from": "profiler_digest", "to": "dataset_understanding", "condition": "dictionary already supplied"},
            {"from": "data_dictionary_generator", "to": "dataset_understanding"},
            {"from": "dataset_understanding", "to": "hitl_semantic_gate"},
            {"from": "hitl_semantic_gate", "to": "rule_candidate_builder"},
            {"from": "rule_candidate_builder", "to": "prompt_customizer"},
            {"from": "prompt_customizer", "to": "rule_proposer"},
            {"from": "rule_proposer", "to": "hitl_gate"},
            {"from": "hitl_gate", "to": "END"},
        ],
    },
    "G_DASHBOARD": {
        "key": "G_DASHBOARD",
        "builder": "build_dashboard_proposal_graph",
        "label_en": "Dashboard proposal (Graph 1B resume)",
        "label_vi": "Đề xuất dashboard (tiếp nối 1B)",
        "run_en": "Run 1 — shortcut",
        "run_vi": "Run 1 — đường tắt",
        "summary_en": "Resumes Graph 1 after semantic review: candidates ➔ prompt ➔ proposal.",
        "summary_vi": "Tiếp nối Graph 1 sau khi duyệt ngữ nghĩa: ứng viên ➔ prompt ➔ đề xuất.",
        "nodes": [
            _node(
                "rule_candidate_builder",
                "Rule candidates",
                "Sinh ứng viên luật",
                DETERMINISTIC,
                "Derive raw technical checks from the confirmed contract.",
                "Sinh kiểm tra kỹ thuật thô từ hợp đồng đã duyệt.",
                inputs=["semantic_contract"],
                outputs=["rule_candidates"],
                source="src/agents/nodes/rule_candidate_builder_node.py",
            ),
            _node(
                "prompt_customizer",
                "Prompt customizer",
                "Tuỳ biến prompt",
                LLM,
                "Rewrite the system prompt for this table's business domain.",
                "Viết lại system prompt theo domain nghiệp vụ của bảng.",
                inputs=["rule_candidates"],
                outputs=["specialized_system_prompts"],
                source="src/agents/nodes/prompt_customizer_node.py",
            ),
            _node(
                "rule_proposer",
                "Rule proposer",
                "Đề xuất luật",
                LLM,
                "Propose rules from the aggregate profile digest.",
                "Đề xuất luật từ digest hồ sơ tổng hợp.",
                inputs=["rule_candidates"],
                outputs=["proposed_rules"],
                db_tables=["rule_proposals"],
                source="src/agents/nodes/rule_proposer_node.py",
            ),
        ],
        "edges": [
            {"from": "rule_candidate_builder", "to": "prompt_customizer"},
            {"from": "prompt_customizer", "to": "rule_proposer"},
            {"from": "rule_proposer", "to": "END"},
        ],
    },
    "G2_DIRECT": {
        "key": "G2_DIRECT",
        "builder": "run_dq_checks",
        # Not a langgraph. This path is plain Python in the job runner, so the
        # catalog/builder drift check must skip it rather than demand a compiled
        # graph that does not exist.
        "langgraph": False,
        "label_en": "Graph 2 · Direct SQL execution",
        "label_vi": "Graph 2 · Thực thi SQL trực tiếp",
        "run_en": "Run 2 — Bounded SQL runner",
        "run_vi": "Run 2 — Bộ chạy SQL có giới hạn",
        "summary_en": "What \"Run approved rules\" actually does: compile approved rules to bounded SQL, refuse anything but a single SELECT, execute under timeout, persist results.",
        "summary_vi": "Đúng những gì nút \"Chạy luật đã duyệt\" làm: biên dịch luật đã duyệt sang SQL có giới hạn, chỉ chấp nhận một câu SELECT, chạy có timeout, rồi lưu kết quả.",
        "nodes": [
            _node(
                "compile_rules",
                "Compile rules",
                "Biên dịch luật",
                DETERMINISTIC,
                "Normalise each rule type and compile it to a bounded SELECT over allow-listed columns.",
                "Chuẩn hoá kiểu luật rồi biên dịch thành câu SELECT có giới hạn trên các cột được cho phép.",
                inputs=["rule_versions", "columns_allowlist"],
                outputs=["compiled_sql", "skipped_rules"],
                db_tables=["rule_versions", "rule_proposals"],
                source="src/services/job_runner.py",
            ),
            _node(
                "validate_sql",
                "Validate SQL",
                "Kiểm định SQL",
                DETERMINISTIC,
                "Reject anything that is not a single SELECT: no semicolons, comments or multi-statements.",
                "Từ chối mọi thứ không phải một câu SELECT duy nhất: không dấu chấm phẩy, chú thích hay đa câu lệnh.",
                inputs=["compiled_sql"],
                outputs=["validated_sql"],
                source="src/services/job_runner.py",
            ),
            _node(
                "execute_checks",
                "Execute checks",
                "Chạy kiểm tra",
                DETERMINISTIC,
                "Run each check against the stored rows under a five-second timeout.",
                "Chạy từng kiểm tra trên dữ liệu đã lưu, giới hạn 5 giây mỗi câu.",
                inputs=["validated_sql"],
                outputs=["checked_count", "failed_count"],
                db_tables=["source_rows"],
                source="src/services/job_runner.py",
            ),
            _node(
                "persist_results",
                "Persist results",
                "Lưu kết quả",
                DETERMINISTIC,
                "Store per-rule outcomes with bounded failed row ids and close the run.",
                "Lưu kết quả từng luật kèm danh sách id dòng lỗi có giới hạn, rồi đóng run.",
                inputs=["checked_count", "failed_count"],
                outputs=["dq_results"],
                db_tables=["dq_results", "dq_runs"],
                source="src/services/job_runner.py",
            ),
        ],
        "edges": [
            {"from": "compile_rules", "to": "validate_sql"},
            {"from": "validate_sql", "to": "execute_checks"},
            {"from": "execute_checks", "to": "persist_results"},
        ],
    },
    "G2": {
        "key": "G2",
        "builder": "build_execution_graph",
        "label_en": "Graph 2 · Deterministic execution",
        "label_vi": "Graph 2 · Thực thi tất định",
        "run_en": "Run 2 — Execution engine",
        "run_vi": "Run 2 — Bộ máy thực thi",
        "summary_en": "Compiles approved rules to dbt tests, gates on validation, runs them, stores results.",
        "summary_vi": "Biên dịch luật đã duyệt sang dbt test, chặn nếu không hợp lệ, chạy và lưu kết quả.",
        "nodes": [
            _node(
                "test_generator",
                "Test generator",
                "Sinh test",
                DETERMINISTIC,
                "Compile approved rules into dbt schema.yml and SQL macros.",
                "Biên dịch luật đã duyệt thành schema.yml và macro SQL của dbt.",
                inputs=["ruleset_versions", "rule_versions"],
                outputs=["generated_tests", "dbt_artifact_ref"],
                db_tables=["ruleset_versions", "rule_versions"],
                source="src/agents/nodes/test_generator_node.py",
            ),
            _node(
                "validate_dbt_project",
                "Validate dbt project",
                "Kiểm định dự án dbt",
                DETERMINISTIC,
                "Scan the generated project for injection and manifest errors.",
                "Quét dự án sinh ra để phát hiện SQL injection và lỗi manifest.",
                inputs=["dbt_artifact_ref"],
                outputs=["dbt_validation_valid", "dbt_validation_error"],
                source="src/agents/nodes/validate_dbt_project_node.py",
            ),
            _node(
                "dbt_validation_failed",
                "Validation failed",
                "Kiểm định thất bại",
                DETERMINISTIC,
                "Fail-closed terminal: mark the run failed and never execute the project.",
                "Điểm dừng fail-closed: đánh dấu run thất bại, không bao giờ thực thi dự án.",
                inputs=["dbt_validation_error"],
                outputs=["error"],
                db_tables=["dq_runs"],
                source="src/agents/graph.py",
            ),
            _node(
                "test_runner",
                "Test runner",
                "Chạy test",
                DETERMINISTIC,
                "Execute the dbt tests under timeout on an isolated connection.",
                "Thực thi dbt test có timeout trên kết nối cách ly.",
                inputs=["generated_tests"],
                outputs=["test_results"],
                source="src/agents/nodes/test_runner_node.py",
            ),
            _node(
                "persist_report",
                "Persist report",
                "Lưu kết quả",
                DETERMINISTIC,
                "Store pass/fail/warn/error outcomes and failing-row samples.",
                "Lưu kết quả đạt/trượt/cảnh báo/lỗi và mẫu dòng lỗi.",
                inputs=["test_results"],
                outputs=["dq_score", "dq_grade"],
                db_tables=["dq_runs", "dq_results"],
                source="src/agents/nodes/persist_report_node.py",
            ),
        ],
        "edges": [
            {"from": "test_generator", "to": "validate_dbt_project"},
            {"from": "validate_dbt_project", "to": "test_runner", "condition": "valid"},
            {"from": "validate_dbt_project", "to": "dbt_validation_failed", "condition": "invalid"},
            {"from": "dbt_validation_failed", "to": "END"},
            {"from": "test_runner", "to": "persist_report"},
            {"from": "persist_report", "to": "END"},
        ],
    },
    "G3": {
        "key": "G3",
        "builder": "build_anomaly_graph",
        "label_en": "Graph 3 · Anomaly & root cause",
        "label_vi": "Graph 3 · Bất thường & nguyên nhân gốc",
        "run_en": "Run 3 — Anomaly DeepAgent",
        "run_vi": "Run 3 — DeepAgent bất thường",
        "summary_en": "Detects statistical anomalies, investigates root cause with read-only tools, writes a report.",
        "summary_vi": "Phát hiện bất thường thống kê, điều tra nguyên nhân bằng tool chỉ đọc, viết báo cáo.",
        "nodes": [
            _node(
                "anomaly_detector",
                "Anomaly detector",
                "Phát hiện bất thường",
                DETERMINISTIC,
                "Run Z-score, IQR, volume drift and out-of-domain detectors.",
                "Chạy Z-score, IQR, trôi khối lượng và tỉ lệ ngoài miền.",
                inputs=["dq_results", "profiles"],
                outputs=["signal_observations", "anomaly_decision"],
                db_tables=["anomaly_runs", "anomaly_signals"],
                source="src/agents/nodes/anomaly_detector_node.py",
            ),
            _node(
                "hypothesis_agent",
                "Hypothesis agent",
                "Agent giả thuyết",
                LLM,
                "ReAct DeepAgent reasoning over five read-only evidence tools.",
                "DeepAgent theo mẫu ReAct suy luận trên năm tool bằng chứng chỉ đọc.",
                inputs=["signal_observations"],
                outputs=["hypotheses"],
                db_tables=["anomaly_hypotheses"],
                source="src/agents/nodes/anomaly_investigation_node.py",
            ),
            _node(
                "persist_analysis",
                "Persist analysis",
                "Lưu phân tích",
                DETERMINISTIC,
                "Store signals and hypotheses with their provenance.",
                "Lưu tín hiệu và giả thuyết kèm nguồn gốc.",
                inputs=["signal_observations", "hypotheses"],
                outputs=["anomaly_status"],
                db_tables=["anomaly_signals", "anomaly_hypotheses"],
                source="src/agents/nodes/persist_analysis_node.py",
            ),
            _node(
                "report_writer",
                "Report writer",
                "Viết báo cáo",
                LLM,
                "Compose the steward-facing Markdown investigation report.",
                "Soạn báo cáo điều tra Markdown cho Data Steward.",
                inputs=["hypotheses"],
                outputs=["steward_report_path"],
                db_tables=["audit_events"],
                source="src/agents/nodes/report_writer_node.py",
            ),
        ],
        "edges": [
            {"from": "anomaly_detector", "to": "hypothesis_agent"},
            {"from": "hypothesis_agent", "to": "persist_analysis"},
            {"from": "persist_analysis", "to": "report_writer"},
            {"from": "report_writer", "to": "END"},
        ],
    },
}


# Which graph backs each wizard step, so the UI can pick without hardcoding keys.
STEP_GRAPHS: dict[str, list[str]] = {
    "UNDERSTAND_DATA": ["G1A"],
    "PROPOSE_RULES": ["G1B"],
    "RUN_CHECKS": ["G2"],
    "ANALYZE_REPORT": ["G3"],
}


def get_catalog() -> dict[str, Any]:
    """Return the full catalog plus the counts the UI shows in headers."""
    graphs = list(GRAPH_CATALOG.values())
    return {
        "graphs": graphs,
        "step_graphs": STEP_GRAPHS,
        "totals": {
            "graphs": len(graphs),
            "nodes": sum(len(graph["nodes"]) for graph in graphs),
            "llm_nodes": sum(1 for graph in graphs for node in graph["nodes"] if node["kind"] == LLM),
            "deterministic_nodes": sum(
                1 for graph in graphs for node in graph["nodes"] if node["kind"] == DETERMINISTIC
            ),
            "gate_nodes": sum(1 for graph in graphs for node in graph["nodes"] if node["kind"] == GATE),
        },
    }


def get_graph(graph_key: str) -> dict[str, Any] | None:
    return GRAPH_CATALOG.get(graph_key)
